### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by Mudock-Yatho**
Fix issue with no new line causing text to scramble together after scan
image

### CODE REVIEW

**Comment by Volkanno** [comment]
UNABLE TO GETH PATH WITH RBXFPSUNLOCKER.DLL

**Comment by Volkanno** [comment]
UNABLE TO GETH PATH WITH RBXFPSUNLOCKER.DLL

**Comment by Volkanno** [comment]
UNABLE TO GETH PATH WITH RBXFPSUNLOCKER.DLL

**Comment by Volkanno** [comment]
UNABLE TO GETH PATH WITH RBXFPSUNLOCKER.DLL

**Comment by Volkanno** [comment]
UNABLE TO GETH PATH WITH RBXFPSUNLOCKER.DLL

**Comment by Pythonic-Rainbow** [comment]
wth, even GitHub has kids to spam nowadays

**Comment by Pythonic-Rainbow** [comment]
If its only for Windows, maybe `\r\n` will be better than `\n`. Not sure about this tho

**Comment by axstin** [comment]
This was intentional in order to reduce spam (the message was printed every 2 seconds)
https://stackoverflow.com/questions/21870545/printing-on-same-line-in-c

**Pull request closed without merging**
