### PR TITLE
Remove instructions for 32 bit

### PR DESCRIPTION
**Pull request by snoopchallenge**

### CODE REVIEW

**Comment by FNFplaye** [comment]
Please help . My fps roblox say fps robox is already running .

**Comment by snoopchallenge** [comment]
> Please help . My fps roblox say fps robox is already running .
im not axstin but id guess that fps unlocker is already running. it shows up in hidden icons so if its not increasing ur fps exit it then reopen then join a roblox game.

**Comment by Modingunreal** [comment]
Yeah They Also Doesn't Put 32Bit On The New Version

**Comment by PhoenixShay** [comment]
Thx

**Pull request merged**
