### PR TITLE
Create fps for strucid

### PR DESCRIPTION
**Pull request by Logan08182007**

### CODE REVIEW

**Comment by Logan08182007** [comment]
hi

**Comment by edgaras1002** [comment]
Bye.

**Comment by edgaras1002** [comment]
Clothes

**Comment by VyperX** [comment]
you guys are retarded

**Comment by VyperX** [comment]
Tf you mean? It’s extremely useful dumbass

**Comment by Corsaka** [comment]
ah yes my mistake this is actually the most important pr ever

**Comment by Reshiram110** [comment]
Github is not the place for cursing and outright derogatory conversations. Take your anger to another platform, seriously.

**Pull request closed without merging**
