### PR TITLE
FPS Unlocker not working - FIXXED 

### PR DESCRIPTION
**Pull request by SEPTYCAL**
**FIX AT BOTTOM**

Before you read this, I have no idea how to use github. I tried submitting an issues, didn't work, so I'm trying this. 

I have an error that keeps occurring each time I try to run FPS unlocker. This is also occurring with any type of injector for ROBLOX. 

Here is an image of the error.

The error occurs whenever you run ROBLOX with the unlocker open. If you know what this means or how to fix it, please let me know, thanks.

Before you say "did you try reinstalling, etc." I guarantee you everything you suggest I've tried, I need someone with experience thanks. 

18a2c5a6385822b44903141e23070a97

**EDIT:** Just wanted to say that this only occurs with the player, not studio. 

**PC Specs**:

Ryzen 7 1800x
RTX 2070 Super
16gb ram
144hz monitor
Windows 10 (Most recent update -- I reinstalled recently) 

The second edit was for adding more of the things listed in "Submitting an Issue" to help axstin when he sees this. 

**Final Edit:** Here's the fix if you need it: https://www.youtube.com/watch?v=pyLZ0FEPBMg&ab_channel=SepticaI

### CODE REVIEW

**Comment by DKANAME** [comment]
Just wanna say I am also having this issue and have tried just about everything

**Comment by ArabiaDiscord** [comment]
Possibly because of the recent roblox update changing the position of TaskScheduler maybe? idk im not a smart guy but we'll have to wait for an update i guess, but until then, we will be suffering with 60 fps

**Comment by SEPTYCAL** [comment]
@axstin

**Comment by Scripter899** [comment]
For me it works.

**Comment by qfoxb** [comment]
It works for me sometimes as well, roblox seems to be keep reverting the change that's breaking fps unlocker

**Comment by DKANAME** [comment]
> For me it works.

To my knowledge, which may be not true at all, some people don't get Roblox updates at the same time that others do, some of my friends have the old cursor still while I have the new one, and their FPS unlocker still works fine. I don't know what exactly has caused this but I believe it's an issue on their side

**Comment by SEPTYCAL** [comment]
> > For me it works.
> 
> To my knowledge, which may be not true at all, some people don't get Roblox updates at the same time that others do, some of my friends have the old cursor still while I have the new one, and their FPS unlocker still works fine. I don't know what exactly has caused this but I believe it's an issue on their side

Do you think I can test this by taking someone's version file and replacing it with my own to see if it works?

**Review by ajthebolt — COMMENTED** [review]
How do I use it

**Comment by Scripter899** [comment]
> How do I use it

1. Install it
2. Run the executable
3. Wait until it closes itself
4. Click the small icon on the taskbar (or Hidden icons drop-up)
5. Set the "FPS cap to 230 (I think)
6. Run a roblox game

**Comment by karenpleasetheyaremykids** [comment]
FPS Unlocker is back to not working, same issue as listed by SEPTYCAL

image

**Comment by SummerPlasma** [comment]
Also having a similar issue after today's update.

**Comment by GoogleHomeboi** [comment]
yep still not working 
‏‏צילום מסך (172)

**Comment by Hawkblob** [comment]
It isn't working for everyone thats using it.

**Comment by coolred246** [comment]
Yeah the recent roblox updated verison isn't compatible with rblxfpsunlocker 4.3.0 so you're gonna have to revert back to the old verison.

**Comment by GoogleHomeboi** [comment]
imma try

**Comment by GoogleHomeboi** [comment]
nope doesn't work in any old version

**Comment by logitchy** [comment]
seems as if nothing can fix it now

**Comment by Lunaticyz** [comment]
roblox got updated recently, my fpsunlocker is not working

**Comment by MustafaDaPro** [comment]
Still broken for me

**Comment by interfolder** [comment]
you can play roblox from the microsoft store until axstin fixes the app, i tried it and it works

**Comment by GoogleHomeboi** [comment]
let's just wait for the fix tbh

**Comment by Josh-sus** [comment]
I tried downloading the new version but it opened as internet explorer, anybody know how to fix this?

**Comment by Josh-sus** [comment]
Roblox is not compatible with 4.3 Version Fps Unlocker, You Have To Use The Old Version 4.2 Or 4.1

**Comment by GoogleHomeboi** [comment]
when you talk to yourself

**Comment by iwantfpsunlocker** [comment]
does anyone know a compatitable fps unlocker to use for now until this one is fixed?

**Comment by GoogleHomeboi** [comment]
i don't know one

**Comment by iwantfpsunlocker** [comment]
> when you talk to yourself

LMAOO

**Comment by GoogleHomeboi** [comment]
i guess well have to wait for the patch

**Comment by Josh-sus** [comment]
Actually im very stupid the other versions don't work neither lol

**Comment by iwantfpsunlocker** [comment]
yeah fr but i dont wanna have to only play on 60 fps smhhh

**Comment by Josh-sus** [comment]
same

**Comment by GoogleHomeboi** [comment]
We'll just have to wait

**Comment by Josh-sus** [comment]
how long tho???

**Comment by iwantfpsunlocker** [comment]
do yall know how long it might take

**Comment by Josh-sus** [comment]
nope i dont know anything

**Comment by GoogleHomeboi** [comment]
i don't think too long

**Comment by iwantfpsunlocker** [comment]
yeah hopefully not

**Comment by GoogleHomeboi** [comment]
last time it was fixed in a day

**Comment by PhoenixShay** [comment]
This isn’t a chat room

**Comment by axstin** [comment]
An update will be coming today

**Pull request closed without merging**
