### PR TITLE
MacOS version

### PR DESCRIPTION
**Pull request by fjij**
I really want to create a version of this for MacOS.

This PR is nowhere near ready (haven't even started) but I wanted to create it now to track my progress.

I was also wondering if someone could give a two sentence summary on how the windows version works.

It would be really helpful to start looking in the right direction.

### CODE REVIEW

**Comment by 11TheOnlyOne1** [comment]
I use a 32-bit windows and it says "can't find taskscheduler i downloaded the old 32-bit on where he said hes not gonna be doing 32 bit. Can Someone help me with that ?

**Comment by 11TheOnlyOne1** [comment]
im trying to find a 32 bit new version but i can't download it due to me having a 32 bit instead of a 64 bit

**Comment by jwhazy** [comment]
Hey, how much do you know about programming on macOS and what language are you thinking of using for the macOS version, still C++? Cheers.

**Comment by SeizureSaladd** [comment]
yo i had the exact same idea and i feel like starting to work on it

the best option for programming language is still C++ but porting all of it will be a pain so if you wanna help lmk (also i kinda suck at c++ regardless of operating system)

**Comment by insyri** [comment]
macos development might be more oriented to objective c/c++ than c++

**Comment by SeizureSaladd** [comment]
> macos development might be more oriented to objective c/c++ than c++

C++ still works fine on macOS and I've ported one file which is settings.cpp so far but it wasn't that much work other than just getting rid of #include <Windows.h> and adding #include <cmath>.

**Comment by jwhazy** [comment]
@insyri do you have any experience in objc or c++?

**Comment by insyri** [comment]
Unfortunately, no, the closest I know is Go and Rust. I was planning to learn c/c++ anyways though, if this gets its feet off the ground, I could try seeing what I can do.
Which fork would you be working on anyways?

**Comment by SeizureSaladd** [comment]
we're gonna have to rewrite the entirety of ui.cpp as it uses window task bar but we can easily rewrite it so that it works on macos menu bar at the top

**Comment by SeizureSaladd** [comment]
here is the settings.cpp file i've ported so far
```cpp
#include "settings.h"
#include "rfu.h"

#include <string>
#include <iostream>
#include <fstream>
#include <functional>
#include <cerrno>
#include <cmath> //cmath required so std::isnan, std::isinf, and std::fmin/fmax don't spew errors

//Ported to macOS by Seizure Salad

const char *advance(const char *ptr)
{
	while (isspace(*ptr)) ptr++;
	return ptr;
}

// scuffed array parse. e.g. [1, 2, 3, 4, 5]
std::vector<double> ParseDoubleArray(const std::string &value, size_t max_elements = 0)
{
	std::vector<double> result;

	auto ptr = advance(value.c_str());
	if (*ptr != '[') throw std::invalid_argument("unexpected character");

	while (++ptr < value.c_str() + value.size())
	{
		ptr = advance(ptr);
		if (*ptr == ']') break;

		errno = 0;

		char *end_ptr;
		double element = std::strtod(ptr, &end_ptr);
		if (errno != 0) throw std::invalid_argument("conversion error");
		if (std::isnan(element)) throw std::invalid_argument("element is nan");
		if (std::isinf(element)) throw std::invalid_argument("element is infinite");
		
		if (max_elements == 0 || result.size() < max_elements) result.push_back(element);
		
		ptr = advance(end_ptr);
		if (*ptr == ']') break;
		if (*ptr != ',') throw std::invalid_argument("unexpected character");
	}

	return result;
}

bool ParseBool(const std::string &value)
{
    //All you do is replace _stricmp with strcmp
	if (strcmp(value.c_str(), "true") == 0) return true;
    if (strcmp(value.c_str(), "false") == 0) return false;
	return std::stoi(value) != 0;
}

std::string BoolToString(bool value)
{
	return value ? "true" : "false";
}

std::string DoubleArrayToString(const std::vector<double> &array)
{
	std::string buffer = "[";
	for (size_t i = 0; i < array.size(); i++)
	{
		if (i > 0) buffer += ", ";
		buffer += std::to_string(array[i]);
	}
	buffer += "]";
	return buffer;
}

namespace Settings
{
	bool VSyncEnabled = false;
	std::vector<double> FPSCapValues = { 30, 60, 75, 120, 144, 165, 240, 360 };
	uint32_t FPSCapSelection = 0;
	double FPSCap = 0.0;
	bool UnlockClient = true;
	bool UnlockStudio = false;
	bool CheckForUpdates = true;
	bool NonBlockingErrors = true;
	bool SilentErrors = false;
	bool QuickStart = false;

	bool Init()
	{
		if (!Load()) Save();
		Update();
		return true;
	}

	// very basic settings parser/writer

	bool Load()
	{
		std::ifstream file("settings");
		if (!file.is_open()) return false;

		printf("Loading settings from file...\n");

		std::string line;

		while (std::getline(file, line))
		{
			size_t eq = line.find('=');
			if (eq != std::string::npos)
			{
				std::string key = line.substr(0, eq);
				std::string value = line.substr(eq + 1);

				try
				{
					if (key == "VSyncEnabled")
						VSyncEnabled = ParseBool(value);
					else if (key == "FPSCapValues")
						FPSCapValues = ParseDoubleArray(value, 100);
					else if (key == "FPSCapSelection")
						FPSCapSelection = std::stoul(value);
					else if (key == "FPSCap")
						FPSCap = std::stod(value);
					else if (key == "UnlockClient")
						UnlockClient = ParseBool(value);
					else if (key == "UnlockStudio")
						UnlockStudio = ParseBool(value);
					else if (key == "CheckForUpdates")
						CheckForUpdates = ParseBool(value);
					else if (key == "NonBlockingErrors")
						NonBlockingErrors = ParseBool(value);
					else if (key == "SilentErrors")
						SilentErrors = ParseBool(value);
					else if (key == "QuickStart")
						QuickStart = ParseBool(value);
				}
				catch (std::exception& e)
				{
					// catch string conversion errors
				}
			}
		}

		if (FPSCapSelection > 0 && FPSCapSelection > FPSCapValues.size())
		{
			FPSCapSelection = 0;
		}

		for (double &value : FPSCapValues)
		{
			value = std::fmin(std::fmax(value, -2147483648.0), 2147483647.0);
		}

		FPSCap = FPSCapSelection == 0 ? 0.0 : FPSCapValues[FPSCapSelection - 1];

		Update();

		return true;
	}

	bool Save()
	{
		std::ofstream file("settings");
		if (!file.is_open()) return false;

		printf("Saving settings to file...\n");

		file << "UnlockClient=" << BoolToString(UnlockClient) << std::endl;
		file << "UnlockStudio=" << BoolToString(UnlockStudio) << std::endl;
		file << "FPSCapValues=" << DoubleArrayToString(FPSCapValues) << std::endl;
		file << "FPSCapSelection=" << std::to_string(FPSCapSelection) << std::endl;
		file << "FPSCap=" << std::to_string(FPSCap) << std::endl;
		file << "CheckForUpdates=" << BoolToString(CheckForUpdates) << std::endl;
		file << "NonBlockingErrors=" << BoolToString(NonBlockingErrors) << std::endl;
		file << "SilentErrors=" << BoolToString(SilentErrors) << std::endl;
		file << "QuickStart=" << BoolToString(QuickStart) << std::endl;

		return true;
	}

	void Update()
	{
		SetFPSCapExternal(FPSCap);
	}
}
```

**Comment by lanylow** [comment]
I'd like to help with that, could anyone share the MacOS roblox client binary with me?

**Comment by insyri** [comment]
Once I get home I'll set up a MacOS VM and send it to you.

**Comment by FireNuke** [comment]
Hi I support the project and looking forward for it! If I could help any way, let me know I use macOS Monterey. Btw I'm not coder.

**Comment by axstin** [comment]
> I'd like to help with that, could anyone share the MacOS roblox client binary with me?

http://setup.roblox.com/mac/version-0430b6cfb6654e77-RobloxPlayer.zip

**Comment by lanylow** [comment]
In the binary posted by axstin, the task scheduler seems to be the variable found at `BF E8 02 00 00 E8 ?? ?? ?? ?? 48 89 C3 48 89 C7 E8 ?? ?? ?? ?? 48 89 1D ?? ?? ?? ??` + 24. I am unable to test if that's right because I don't own any mac machine, neither any GPU from AMD. At this point it should be fairly easy to find the frame delay offset and make a simple FPS unlocker, I'd try coding that if I could. For anyone attempting, good luck.
image

**Comment by SeizureSaladd** [comment]
> In the binary posted by axstin, the task scheduler seems to be the variable found at `BF E8 02 00 00 E8 ?? ?? ?? ?? 48 89 C3 48 89 C7 E8 ?? ?? ?? ?? 48 89 1D ?? ?? ?? ??` + 24. I am unable to test if that's right because I don't own any mac machine, neither any GPU from AMD. At this point it should be fairly easy to find the frame delay offset and make a simple FPS unlocker, I'd try coding that if I could. For anyone attempting, good luck.
> image

hey I own a Mac and I can send you the macOS binary. I'm pretty sure that the binary above is for windows but I'm not sure. If you wanna contact me you can via discord seizure salad#3820 or via email seizure.salad.stuff@gmail.com and I can send you the binary.

**Comment by lanylow** [comment]
Hello, I've been trying to make a function that would get the base address of the roblox module, but I myself can't get it to work. If anyone is able to make a working one for MacOS, post it here.

**Comment by SeizureSaladd** [comment]
> Hello, I've been trying to make a function that would get the base address of the roblox module, but I myself can't get it to work. If anyone is able to make a working one for MacOS, post it here.
> 
> Edit: It took us 3 days to realize that we have to run it as root, it works fine now.

WOO BABY WE'RE MAKING GOOD PROGRESS

**Comment by SeizureSaladd** [comment]
update: we got it to work lol
image

**Comment by lanylow** [comment]
Hello, yeah we got it working. Thanks @SeizureSaladd for testing all the code for me, I wouldn't be able to code anything if not them :).
```
#include <stdio.h>
#include <stdlib.h>
#include <cstdint>
#include <stdexcept>

#include <mach/mach_traps.h>
#include <mach/mach_init.h>
#include <mach/mach_error.h>
#include <mach/mach.h>
#include <mach-o/dyld_images.h>
#include <libproc.h>

struct {
  pid_t id = 0;
  mach_port_t task = 0;
  mach_vm_address_t load_address = 0;
  off_t size = 0;
} roblox;

pid_t get_roblox_process_id() {
  auto proc_cnt = proc_listpids(PROC_ALL_PIDS, 0, nullptr, 0);

  pid_t ids[proc_cnt];
  bzero(ids, sizeof(ids));
  proc_listpids(PROC_ALL_PIDS, 0, ids, (int)sizeof(ids));

  for (auto i = proc_cnt; i > 0; --i) {
    if (ids[i] == 0) continue;

    char path[PROC_PIDPATHINFO_MAXSIZE];
    bzero(path, sizeof(path));
    proc_pidpath(ids[i], path, sizeof(path));

    char name[256];
    bzero(name, sizeof(name));

    auto pos = strlen(path);
    while (pos >= 0 && path[pos] != '/') pos--;

    strcpy(name, path + pos + 1);
    if (strcmp(name, "RobloxPlayer") == 0) return ids[i];
  }

  return 0;
}

bool init_roblox_struct() {
  roblox.id = get_roblox_process_id();
  if (!roblox.id) return false;

  task_for_pid(mach_task_self(), roblox.id, &roblox.task);
  if (!roblox.task) return false;

  struct task_dyld_info dyld_info;
  mach_msg_type_number_t task_info_cnt = TASK_DYLD_INFO_COUNT;
  mach_vm_address_t address = 0;
  if (task_info(roblox.task, TASK_DYLD_INFO, (task_info_t)&dyld_info, &task_info_cnt) == KERN_SUCCESS) address = dyld_info.all_image_info_addr;

  mach_msg_type_number_t size = sizeof(struct dyld_all_image_infos);
  vm_offset_t read_buffer;
  if (vm_read(roblox.task, address, size, &read_buffer, &size) != KERN_SUCCESS) return false;
  auto image_infos = (struct dyld_all_image_infos *)read_buffer;

  size = 24 * image_infos->infoArrayCount;
  if (vm_read(roblox.task, (mach_vm_address_t)image_infos->infoArray, size, &read_buffer, &size) != KERN_SUCCESS) return false;
  auto info = (struct dyld_image_info*)read_buffer;
  
  for (auto i = 0; i < image_infos->infoArrayCount; i++) {
    size = 1024;
    vm_read(roblox.task, (mach_vm_address_t)info[i].imageFilePath, size, &read_buffer, &size);
    auto path = (char*)read_buffer;

    if (!path) continue;
    if (strstr(path, "/RobloxPlayer") == NULL) continue;

    struct stat st;
    stat(path, &st);

    roblox.load_address = (mach_vm_address_t)info[i].imageLoadAddress;
    roblox.size = st.st_size;
  }

  if (!roblox.load_address || !roblox.size) return false;
  return true;
}

template <typename T>
T read_memory(mach_vm_address_t address, off_t size = sizeof(T)) {
  T buff{};
  vm_offset_t data;
  mach_msg_type_number_t sz;

  if (vm_read(roblox.task, (vm_address_t)address, size, &data, &sz) == KERN_SUCCESS) {
    buff = (T)(*(T*)(data));
    vm_deallocate(current_task(), data, sz);
  }

  return buff;
}

uint8_t* read_data(mach_vm_address_t address, off_t size) {
  vm_offset_t data;
  mach_msg_type_number_t sz;

  if (vm_read(roblox.task, (vm_address_t)address, size, &data, &sz) != KERN_SUCCESS) return nullptr;

  return (uint8_t*)data;
}

template <typename T>
void write_memory(mach_vm_address_t address, T data) {
  vm_write(roblox.task, (vm_address_t)address, (vm_offset_t)&data, sizeof(data));
}

bool compare(uint8_t* data, uint8_t* sig, uint32_t size) {
  for (auto i = 0; i < size; i++)
    if (data[i] != sig[i] && sig[i] != 0x00)
      return false;
  return true;
}

uint8_t* find_sig(void* start, void* end, const char* sig, uint32_t size) {
  for (auto i = (uint8_t*)start; i < (uint8_t*)end - size; i++)
    if (compare(i, (uint8_t*)sig, size))
      return i;
  return 0;
}

mach_vm_address_t find_task_scheduler() {
  auto data = read_data(roblox.load_address, roblox.size);
  auto address = (uintptr_t)find_sig(data, data + roblox.size, "\xBF\xE8\x02\x00\x00\xE8\x00\x00\x00\x00\x48\x89\xC3\x48\x89\xC7\xE8\x00\x00\x00\x00\x48\x89\x1D\x00\x00\x00\x00", 28);

  if (!address) throw std::runtime_error("Couldn't find the task scheduler pattern.");

  mach_vm_address_t res = roblox.load_address + ((address + *(uint32_t*)(address + 24) + 28) - (mach_vm_address_t)data);
  vm_deallocate(current_task(), (vm_offset_t)data, roblox.size);

  return res;
}

int main(int argc, char** argv) {
  if (!init_roblox_struct()) throw std::runtime_error("Failed to get roblox process info.");

  printf("Roblox process id: %d\n", roblox.id);
  printf("Roblox module address: 0x%llx\n", roblox.load_address);
  printf("Roblox module size: 0x%llx\n", roblox.size);

  auto task_scheduler_pointer = find_task_scheduler();
  printf("Task scheduler pointer: 0x%llx\n", task_scheduler_pointer);
  
  auto task_sheduler = read_memory<mach_vm_address_t>(task_scheduler_pointer);
  printf("Task scheduler: 0x%llx\n", task_sheduler);

  write_memory<double>(task_sheduler + 0x130, (double)(1.0 / 360.0));

  return 0;
}
```

**Comment by FireNuke** [comment]
How to run the code?

**Comment by lanylow** [comment]
> How to run the code?

Compile it in xcode and run as root from terminal.

**Comment by FireNuke** [comment]
> > How to run the code?
> 
> Compile it in xcode and run as root from terminal.

Thanks. Btw will there be normal launcher for Mac fps unlocker or no?

**Comment by SeizureSaladd** [comment]
> > > How to run the code?
> > 
> > 
> > Compile it in xcode and run as root from terminal.
> 
> Thanks. Btw will there be normal launcher for Mac fps unlocker or no?

i'm working on frontend for it so it will have the same features as the windows one hopefully

**Comment by P3tray** [comment]
Great work lads, real nice.

Now all we need is a Linux port as Roblox runs in Wine.

**Comment by SeizureSaladd** [comment]
> Great work lads, real nice.
> 
> Now all we need is a Linux port as Roblox runs in Wine.

this should also run on linux i think but idk

**Comment by P3tray** [comment]
> > Great work lads, real nice.
> > Now all we need is a Linux port as Roblox runs in Wine.
> 
> this should also run on linux i think but idk

Was saying something similar but ya edited it.

**Comment by P3tray** [comment]
Don't forget to include changes to the readme


> 6.    Does this work for Mac?
> 
> No. Roblox FPS Unlocker was written only for the Windows platform and I currently have no plans to change this. However, those more experienced and with Mac hardware are free to port this project to Mac!

**Comment by lanylow** [comment]
> Great work lads, real nice.
> 
> 
> 
> Now all we need is a Linux port as Roblox runs in Wine.

No point in making a native unlocker for non-native game. There is a tool called GrapeJuice that allows you to run both roblox and fps unlocker on linux.

**Comment by P3tray** [comment]
> > Great work lads, real nice.
> > Now all we need is a Linux port as Roblox runs in Wine.
> 
> No point in making a native unlocker for non-native game. There is a tool called GrapeJuice that allows you to run both roblox and fps unlocker on linux.

News to me, that's cool.

**Comment by fjij** [comment]
for those don't know how to run it, save it to `main.cpp` then compile it:
```sh
g++ --std=c++11 ./main.cpp
```

then run it while roblox is running
```sh
sudo ./a.out
```

@lanylow @SeizureSaladd

this is awesome :D do you want to add to the branch? or you can create your own

i sent an collaborator invite -- i'm not sure if it's the best way to do it but ? :D

**Comment by lanylow** [comment]
Hi fjij, we already created a repository on my profile. The code and release build will be published shortly.

**Comment by fjij** [comment]
Sweet :D

**Comment by fjij** [comment]
I'll close this PR then.

For anyone in the future that finds this:

https://github.com/lanylow/rbxfpsunlocker-osx

!!!

**Comment by DevVanish** [comment]
Good luck yo

**Pull request closed without merging**
