### PR TITLE
Updated icon

### PR DESCRIPTION
**Pull request by mxdanger**
Update to the tray app icon.

Here's an image showing what the new icon looks like.
RobloxUnlockFPS

Heres the .ico file being used in the startmenu and the console.
image
image

### CODE REVIEW

**Comment by mxdanger** [comment]
The icon is #FFF white and if you want I can make a black version of it if that’s needed.

**Comment by LewisTehMinerz** [comment]
@mxdanger I'm going to be writing a fork of RFU to make some improvements over v4.2.0, then possibly merge back into this repository. Do you mind if I use this icon?

**Comment by mxdanger** [comment]
@LewisTehMinerz Sure, but the reason the icon is white is that it blends into the rest of the tray icons. The Red color you are using makes it look out of place.

image

**Comment by LewisTehMinerz** [comment]
Yeah, it's what I feared, but on light theme/white title bars the icon is either really hard to see or invisible.

**Comment by Corsaka** [comment]
Most OS don't support white title bars for that exact reason.

**Comment by LewisTehMinerz** [comment]
@Corsaka But considering that the only operating system this tool works for does we have to take it into account. We also have to consider that the white title bars are default on Windows 10. Designing graphics for software is hard for this exact reason and compromises have to be made.

I was actually going to try and figure out how to switch the icon depending on theme (so a dark icon on light themes and vice versa) but I never got around to doing it. Maybe it's worth doing now since I have a bit more knowledge of what I need to do to get this value.

**Comment by Corsaka** [comment]
> We also have to consider that the white title bars are default on Windows 10. 

No they're not? Windows 10 explicitly doesn't support that colour of title bar BECAUSE they haven't introduced contrast for their icons.
image

**Comment by LewisTehMinerz** [comment]
image
Uncheck this.

**Comment by Corsaka** [comment]
Ah, I see - light mode. Disgusting.

In that case, we need to figure out how Windows does contrasting icons like that and introduce it for RFU - or just put a black border around a white icon like discord does.

**Comment by LewisTehMinerz** [comment]
I added it to (my version of) RFU. Registry keys and handling multiple icons. It's at `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize`.

When mixing themes, these are what the options map to.
`AppsUseLightTheme` is this option (styles just apps, primarily UWP):
image
`SystemUsesLightTheme` is this option (styles everything else):
image
`0` is dark theme and `1` is light theme.

**Comment by Corsaka** [comment]
Wish I understood C++ so I could actually contribute rather than passive-aggressively talk at other people online.

**Comment by SymzYT** [comment]
Yo, totally getting new release!

**Comment by Pikachu459** [comment]
New Icon doesn't make the program better .

**Comment by mxdanger** [comment]
> New Icon doesn't make the program better.

This pull is only for a new icon and doesn't change anything else.

**Comment by mxdanger** [comment]
I wonder if this ended up being a waste of my time as @axstin has never made any response since I made this pull nearly a year ago.

**Comment by LewisTehMinerz** [comment]
Stuff happens I guess @mxdanger.

**Comment by panda175** [comment]
Can you make it so that mobile & phone player can use the Fps unlocker

**Comment by LewisTehMinerz** [comment]
@panda175 This is unrelated to this PR but it'd be impossible to make an FPS unlocker for mobile that doesn't violate some sort of terms of service or requires you to do some weird stuff to your device.

**Comment by mxdanger** [comment]
@panda175 @LewisTehMinerz What you are talking about is off topic and unrelated to this pull request. Please consider deleting your comment and creating issue instead.

**Comment by bbzlazer** [comment]
Has been almost a year and this hasn't been accepted

we rly need this accepted, tried of getting the icon mixed up with roblox

**Comment by KcTec90** [comment]
axstin probably isn't active that  much anymore :/

**Comment by KcTec90** [comment]
uhh ok

**Pull request merged**
