### PR TITLE
Add 165 and 360 fps caps selection

### PR DESCRIPTION
**Pull request by AntoSkate**

### CODE REVIEW

**Comment by safazi** [comment]
yes please merge it now thanks 👍🏻 any day now

**Comment by Gluvii** [comment]
Can you add 180 fps cap too?

**Comment by Francisjerouslawas** [comment]
Hi

**Comment by Francisjerouslawas** [comment]
Please Give Low Ping On roblox

**Comment by AntoSkate** [comment]
> Please Give Low Ping On roblox

what do you mean by "low ping"? this program only disable vsync to allow higher fps than 60, it doesn't change ping or other things

**Comment by AntoSkate** [comment]
> Can you add 180 fps cap too?
> and how do you add it?

sure, i'll add it soon

**Comment by AntoSkate** [comment]
@Gluvii in the meantime you can change the maximum fps manually in the settings file

**Comment by AntoSkate** [comment]
Done, i added the 180 fps cap. You can find the program in the Releases tab on my fork

**Comment by ghrave** [comment]
Why is the FPS capping on my monitor's refresh rate? I have my FPS cap on none and it's still not going above 180 FPS which is my monitor's hz, and also I don't even have VSYNC enabled on the Nvidia control panel.

**Comment by axstin** [comment]
Hi, I figured the best solution here would be to implement configurable FPS cap values: https://github.com/axstin/rbxfpsunlocker/commit/c0a426bb988d675ea62e730f0700845b781ad8d4
165 and 360 were also added to the default list.

**Comment by Gluvii** [comment]
> Hi, I figured the best solution here would be to implement user-configurable FPS cap values: [c0a426b](https://github.com/axstin/rbxfpsunlocker/commit/c0a426bb988d675ea62e730f0700845b781ad8d4)
> 165 and 360 were also added to the default list.

Can you add 180 too

**Comment by AntoSkate** [comment]
> 
> 
> > Hi, I figured the best solution here would be to implement user-configurable FPS cap values: [c0a426b](https://github.com/axstin/rbxfpsunlocker/commit/c0a426bb988d675ea62e730f0700845b781ad8d4)
> > 165 and 360 were also added to the default list.
> 
> Can you add 180 too

You can add a custom cap value changing "FPSCapValues" in the settings file

**Pull request closed without merging**
