### PR TITLE
Add new macOS version

### PR DESCRIPTION
**Pull request by SeizureSaladd**
Recently me and @lanylow have created an FPS unlocker for macOS, and I changed the README so people who want to find it can.

### CODE REVIEW

**Comment by axstin** [comment]
I'll be watching how this project matures and add it to the README in due time ;). I've waited ~3 years to see if someone would take the initiative; props to you guys for doing so!

**Comment by SeizureSaladd** [comment]
> I'll be watching how this project matures and add it to the README in due time ;). I've waited ~3 years to see if someone would take the initiative; props to you guys for doing so!

Thanks! We're working on a new update which will add a user interface instead of just it being a command line tool which will hopefully make it more user friendly and will be more like a port of the windows version.

**Comment by Buddelbubi** [comment]
Sorry that I have to write here, but I cant find any other way to message you.
Please update so it works with the microsoft store version.
The roblox player seems to have a bug where you cant play due unexpected client behaviour on windows 11.
The microstoft store version works just fine, but is unplayable due its low fps.

**Comment by jorge0343** [comment]
hi I tried downloading this on my Mac and it didn't work?

**Comment by lanylow** [comment]
> hi I tried downloading this on my Mac and it didn't work?

Create an issue in our repo then, not here.
https://github.com/lanylow/rbxfpsunlocker-osx

**Comment by ztik** [comment]
I'm so proud of lanylow and axstin and other developers, Thank you guys for making roblox great.

**Comment by Xyn0w** [comment]
Axstin, please return fps unlocker for 32 bit operating systems, I know there are many false virus alerts, But it is very necessary for us low end pc (32 bit) that we can't have a good pc, Please axtin.

**Comment by Xyn0w** [comment]
Axstin, please return fps unlocker for 32 bit operating systems, I know there are many false virus alerts, But it is very necessary for us low end pc (32 bit) that we can't have a good pc, Please axtin.

**Comment by Xyn0w** [comment]
> I'll be watching how this project matures and add it to the README in due time ;). I've waited ~3 years to see if someone would take the initiative; props to you guys for doing so!

Axstin, please return fps unlocker for 32 bit operating systems, I know there are many false virus alerts, But it is very necessary for us low end pc (32 bit) that we can't have a good pc, Please axtin.

**Comment by insyri** [comment]
You can compile it yourself.

**Comment by PhoenixShay** [comment]
At this time Austin has decided to keep the repositories separate. Great work

**Pull request closed without merging**
