### PR TITLE
Add file version info resource

### PR DESCRIPTION
**Pull request by pizzaboxer**
Primarily added this as an easier way to check the unlocker version purely from the executable file itself without having to run it. Aside from version information, it also adds author information and a bunch of other stuff. Don't really know why it decided to separate English US and English UK, but it should be fine.

### CODE REVIEW

**Comment by PhoenixShay** [comment]
wow !

**Comment by BUNNY5470** [comment]
your a giga chad bro tysm you don't know how it feels working with a bad
laptop for over like 20 years

‫في الأحد، 15 يناير 2023 في 10:41 م تمت كتابة ما يلي بواسطة ‪pizzaboxer‬‏ <‪
***@***.***‬‏>:‬

**Comment by Hasster1** [comment]
I am sorry for spamming this, but it looks like someone stole code for this project, and selling it on the microsoft website
https://www.microsoft.com/en-us/p/fps-unlocker/9mzfh421pwx1?activetab=pivot:overviewtab

**Comment by pizzaboxer** [comment]
> I am sorry for spamming this, but it looks like someone stole code for this project, and selling it on the microsoft website https://www.microsoft.com/en-us/p/fps-unlocker/9mzfh421pwx1?activetab=pivot:overviewtab

The [license](https://github.com/axstin/rbxfpsunlocker/blob/master/LICENSE) actually permits anyone to resell the software. The real problem would be if whoever's reselling it doesn't include a copy of the license. Does it include a copy?

**Comment by axstin** [comment]
Apologies for never merging this 😔

**Pull request closed without merging**
